### ISSUE TITLE
Error when adding the seo plugin to my payload.config.ts: Unexpected token 'export'

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/plugin-seo#1]
The moment I add the seo object to my payload.config.ts, I'm getting the following error:
```
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/server.ts`
[19:26:15] INFO (payload): Starting Payload...
C:\Coding\GitHub\wheelcosmos-payload\node_modules\.pnpm\payload@0.15.7_ts-node@9.1.1+typescript@4.6.3\node_modules\payload\components\forms.ts:1
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._compile (C:\Coding\GitHub\wheelcosmos-payload\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at require.extensions.<computed> (C:\Coding\GitHub\wheelcosmos-payload\node_modules\.pnpm\ts-node@9.1.1_typescript@4.6.3\node_modules\ts-node\src\index.ts:1045:43)
    at Object.newLoader [as .ts] (C:\Coding\GitHub\wheelcosmos-payload\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[nodemon] app crashed - waiting for file changes before starting...
```

My payload.config.ts:
```ts
import { buildConfig } from 'payload/config';
import path from 'path';
import Categories from './collections/Categories';
import Posts from './collections/Posts';
import Tags from './collections/Tags';
import Users from './collections/Users';
import PostTest from './collections/PostsTest';
import Media from './collections/Media';
import seo from 'payload-plugin-seo';

export default buildConfig({
  serverURL: 'http://localhost:3000',
  admin: {
    user: Users.slug,
  },
  collections: [
    Categories,
    Posts,
    Tags,
    Users,
    PostTest,
    Media
  ],
  plugins: [
    seo({
      collections: [
        'posts-test',
      ],
      uploadsCollection: 'media',
      generateTitle: ({ doc }) => `WheelCosmos.com — ${doc.title}`,
      generateDescription: ({ doc }) => doc.excerpt
    })
  ],
  localization: {
    locales: [
      'en-SG',
      'de-DE',
    ],
    defaultLocale: 'en-SG',
    fallback: false,
  },
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts')
  },
});
```

My package.json:
```json
{
  "name": "payload-blog-typescript",
  "description": "Blog template",
  "version": "1.0.0",
  "main": "dist/server.js",
  "license": "MIT",
  "scripts": {
    "dev": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon",
    "build:payload": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build",
    "build:server": "tsc",
    "build": "yarn build:payload && yarn build:server",
    "serve": "cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js",
    "generate:types": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:types"
  },
  "dependencies": {
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "^0.15.7",
    "payload-plugin-seo": "^0.0.4"
  },
  "devDependencies": {
    "@types/express": "^4.17.9",
    "cross-env": "^7.0.3",
    "nodemon": "^2.0.6",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  }
}
```

If the seo() object is empty, I'm getting the same error. Removing the seo() object fixes it.

**Comment by jacobsfletch** [comment]
Hi @AlessioGr! Happy to help here. Could you send me your `tsconfig`? So far I'm unable to recreate your error.

**Comment by AlessioGr** [comment]
> > Hi @AlessioGr! Happy to help here. Could you send me your `tsconfig`? So far I'm unable to recreate your error.
> 
> Check specifically for `esModuleInterop` and set to `true`, if not already.

Hey,
esModuleInterop is true already. I have added you as a collaborator to my repo so you can check it out easier:
https://github.com/AlessioGr/wheelcosmos-payload/blob/master/tsconfig.json

**Comment by jacobsfletch** [comment]
@AlessioGr thanks for sending this over. I cloned your repo down, and was able to spin it up without errors. I'm wondering if it could be your dependency manager? I see you're using `pnpm` instead of `yarn`. It could be that your `pnpm-lock.yaml` file is out of date.

I went ahead and installed everything with yarn, and pushed [a copy of my branch]([pnpm](https://github.com/AlessioGr/wheelcosmos-payload/blob/fix/ts-errors/pnpm-lock.yaml)) so you could take a look. Clone it down, then run `yarn && yarn dev`.

**Comment by AlessioGr** [comment]
> @AlessioGr thanks for sending this over. I cloned your repo down, and was able to spin it up without errors. I'm wondering if it could be your dependency manager? I see you're using `pnpm` instead of `yarn`. It could be that your `pnpm-lock.yaml` file is out of date.
> 
> I went ahead and installed everything with yarn, and pushed a copy of my branch so you could take a look. Clone it down, then run `yarn && yarn dev`.

Thank you a lot, you're completely right! It does not work with pnpm - even after I deleted the pnpm-lock.yaml and tried it again. With yarn it works perfectly!

I also want to note that it also doesn't work on npm. In fact, the npm install command doesn't work in the first place:
```
PS C:\Coding\GitHub\wheelcosmos-payload> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: payload-blog-typescript@1.0.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.0.0" from @payloadcms/config-provider@1.0.1
npm ERR!   node_modules/@payloadcms/config-provider
npm ERR!     peer @payloadcms/config-provider@"^1.0.0" from payload-plugin-seo@0.0.4
npm ERR!     node_modules/payload-plugin-seo
npm ERR!       payload-plugin-seo@"^0.0.4" from the root project
npm ERR!     @payloadcms/config-provider@"^1.0.0" from payload@0.15.7
npm ERR!     node_modules/payload
npm ERR!       payload@"^0.15.7" from the root project
npm ERR!       1 more (payload-plugin-seo)
npm ERR!   peer react@">=15" from react-router-dom@5.3.1
npm ERR!   node_modules/react-router-dom
npm ERR!     peer react-router-dom@"^5.2.0" from @payloadcms/config-provider@1.0.1
npm ERR!     node_modules/@payloadcms/config-provider
npm ERR!       peer @payloadcms/config-provider@"^1.0.0" from payload-plugin-seo@0.0.4
npm ERR!       node_modules/payload-plugin-seo
npm ERR!         payload-plugin-seo@"^0.0.4" from the root project
npm ERR!       1 more (payload)
npm ERR!     react-router-dom@"^5.1.2" from payload@0.15.7
npm ERR!     node_modules/payload
npm ERR!       payload@"^0.15.7" from the root project
npm ERR!       1 more (payload-plugin-seo)
npm ERR!   1 more (payload)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from payload-plugin-seo@0.0.4
npm ERR! node_modules/payload-plugin-seo
npm ERR!   payload-plugin-seo@"^0.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\aless\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aless\AppData\Local\npm-cache\_logs\2022-04-18T17_28_52_112Z-debug-0.log
```

Any idea if there might be a dependency issue?

**Comment by jacobsfletch** [comment]
@AlessioGr Aha so glad this worked for you!

Yes, these errors look familiar to me. Payload is actively updating to React 18, and it seems we're getting in the middle of that update. Yarn is probably able to better resolve these types of dependency issues.

For now, I think you can decrement the `@payloadcms/config-provider` down to version `1.0.0`. It looks like this is the module depending on it.

I hope that this unblocks you for now! I'll report back with an update once payload finishes migrating to React 18, so these plugins can follow suit.

**Comment by AlessioGr** [comment]
> @AlessioGr Aha so glad this worked for you!
> 
> Yes, these errors look familiar to me. Payload is actively updating to React 18, and it seems we're getting in the middle of that update. Yarn is probably able to better resolve these types of dependency issues.
> 
> For now, I think you can decrement the `@payloadcms/config-provider` down to version `1.0.0`. It looks like this is the module depending on it.
> 
> I hope that this unblocks you for now! I'll report back with an update once payload finishes migrating to React 18, so these plugins can follow suit.

Aah I see, thank you! I'll just keep using yarn until this is resolved, then.
In the Chrome dev tools console, I'm getting this error, by the way:
![image](https://user-images.githubusercontent.com/70709113/163851111-3609d2b7-62c7-4639-b954-010f8535f3c8.png)
Is this in any way related?

**Comment by jacobsfletch** [comment]
@AlessioGr you got it, this is also related to the React 18 update. That specific issue is related to new React [root API](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis).

It looks like Payload version `0.15.7` installs React 18. So you can either go down to version `0.15.6` or ignore the error until everything is resolved permanently (I don't think this is a breaking change).

**Comment by AlessioGr** [comment]
Aah I see, okay! I haven't noticed any actual side effects yet, so I'm going to just ignore that one for now!

**Comment by jacobsfletch** [comment]
Hey @AlessioGr! Payload is now officially on React 18. Everything should be resolved with in the latest version. If you want to give it a shot, run `yarn add payload@^0.16.1` and let me know how it goes!
