### ISSUE TITLE
Access to the local payload API inside a generate function

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/plugin-seo#10]
For a generate function I want to get data from the settings page like this.

```
      generateDescription: async ({ doc, locale }) => {
        const settings = await payload.findGlobal({
          slug: 'settings',
          overrideAccess: true,
          depth: 1,
        });
        return settings?.fields?.defaultDescription?.value;
      }
```

Thing is that its running client side so is there a way to access the payload api easy in the generate function?

Normaly it would be accesable via the req.payload object.

**Comment by jacobsfletch** [comment]
Hi @matthijs166 I'm digging into this one. The question really comes down to whether you should import Payload from your callback, or the the React component imports it and sends it through to you.

**Comment by jacobsfletch** [comment]
Ok @matthijs166 after second thought, this one is pretty simple. We're in a React component, so we won't have access to Payload local API (we're in a browser). Instead, use would just use the [REST API](https://payloadcms.com/docs/rest-api/overview) or [GraphQL](https://payloadcms.com/docs/graphql/overview) as needed.

**Comment by matthijs166** [comment]
Thanks! I see that I can use fetch directly without the need of authentication because the auth is set inside a cookie.

Would be cleaner to get the values without an extra fetch but dont think its easy to implement. Or it need to be build in a way like yoast SEO with the use of snippets variabels: https://yoast.com/help/list-available-snippet-variables-yoast-seo/

**Comment by jacobsfletch** [comment]
@matthijs166 YES! That is exactly what we've got in store for the future of this plugin. This same pattern will apply across a few other plugins as well, like the form builder.
