### ISSUE TITLE
Feat Request: Add an example to set generate via fields from a settings page

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/plugin-seo#12]
I almost have the generate working with values from a settings page.

Is it an idea to add it as an example? And so where is the best place? In the readme or in a separate example folder inside the project?

**Comment by jacobsfletch** [comment]
Hey @matthijs166! Totally, the best place for this is the working demo in the repo [here](https://github.com/payloadcms/plugin-seo/blob/main/demo/src/payload.config.ts)

**Comment by Rar9** [comment]
I need to reopen this for better understanding. 

I have some fields called Titel other are called Name.... 

My description field vary even more.

How to implement this variation for AUTOCOMPLETE if all is located in payload config and Not in the individual content pages? 

In addition I like to add automatically assign the content first image, so storing in yet another new file makes no sense as I only require a link to gibe media. 

Lastly I like to use the seo in a tabs system on content, so scrolling is mininised like content/images/seo

How can all this be archived?
