### ISSUE TITLE
Populate Open Graph metadata

### ISSUE THREAD

**Issue by Rar9** [payloadcms/plugin-seo#13]
This plugin seams to offer the Basic SEO fields

Will it at some point support also other social post option like

OpenGraph / Twitter Cards  and other advanced meta field like geolocations

to get something like 

https://www.opengraph.xyz/url/https%3A%2F%2Fpayloadcms.com

**Comment by jacobsfletch** [comment]
Hey @Rar9 we currently rely on the developers' front-end to populate their open-graph meta programatically. Although I think this could be a great feature which would take some logic out of the front-end. I'll label this as a feature and keep it open.

**Comment by Rar9** [comment]
Default stuff like content generator, or geolocation can be included on frontend. 

Backend advanced SEO to set something like robots for index / follow...

Getting optional dedicated fields for social share like opengraph allows for very flexible and optimal posts

**Comment by jacobsfletch** [comment]
Closing this issue because OG metadata is out of scope for this plugin. Both yoast and opengraph.xyz rely on the same three base fields at this plugin, which are title, description, and image.
