### ISSUE TITLE
Re-Use fancy Min/Max Lenght for other fields

### ISSUE THREAD

**Issue by Rar9** [payloadcms/plugin-seo#15]
Is its somehow possible to re-use  `LengthIndicator.tsx`  to be used with other payload fieds to display a fancy max length??

**Comment by jacobsfletch** [comment]
Hey @Rar9 this is certainly possible, it would just need to be shipped in [Payload core](https://github.com/payloadcms/payload), then imported here in this plugin or from anywhere in your own project. Certainly possible but would be considered a feature request.
