### ISSUE TITLE
Validation issue on save

### ISSUE THREAD

**Issue by ChristopherNowlan** [payloadcms/plugin-seo#17]
ValidationError: _pages_versions validation failed: version.meta.image: Cast to Embedded failed for value "[object Object]" (type string) at path "image" because of "ObjectExpectedError".

Not sure if above is an issue or something I haven't done correctly

**Comment by ChristopherNowlan** [comment]
Hey @jacobsfletch forgot to mention the issue happens when I add a image to the meta image field generated by the seo plugin.

**Comment by jacobsfletch** [comment]
Hey @ChristopherNowlan are you still experiencing this issue? I was not able to reproduce it using this plugin's demo. Here's a screen-recording:

https://user-images.githubusercontent.com/15735305/202566579-fbe43a10-8c64-4d73-82bd-2c78d6230d94.mp4

If you're able to reproduce this in an isolated way, feel free to re-open this issue with instructions so I can do the same.

**Comment by ChristopherNowlan** [comment]
@jacobsfletch I get issue when I add below to the pages collection. Without it there is no issue.
`{
	name: 'featureImage',
	label: 'Feature Image',
	type: 'upload',
        relationTo: 'media',
},`
