### ISSUE TITLE
Disable tabs nesting

### ISSUE THREAD

**Issue by Kikky** [payloadcms/plugin-seo#18]
### When I use **tabbedUI: true** and tabs in the document I get such tabs structure:
_______________
Content - SEO
_______________
MyTab1 - MyTab2
________________
### But I expect to get such structure:
________________
MyTab1 - MyTab2 - SEO
________________

See screenshot:

![seo](https://user-images.githubusercontent.com/614922/195788260-c86f7606-2fd5-4881-822e-386c430892a3.png)

Is there a way to do this?

Thanks in advance! And thanks for this plugin!

**Comment by jacobsfletch** [comment]
Hey @Kikky, I'm pretty sure [this PR](https://github.com/payloadcms/plugin-seo/pull/25) is exactly the fix you're looking for! It will go out in the next release. I'll keep this issue open until that happens.

**Comment by jacobsfletch** [comment]
Ok `1.0.9` is out, so you can give it a shot!
