### ISSUE TITLE
Search by ID only with tabbedUI: true

### ISSUE THREAD

**Issue by Kikky** [payloadcms/plugin-seo#19]
Also when I use **tabbedUI: true** only searching by ID is available on collection's page:

![search](https://user-images.githubusercontent.com/614922/195809193-de9fe1fe-9222-48a5-be3f-b8cf8a6184a4.png)

Without **tabbedUI: true**:

![search_2](https://user-images.githubusercontent.com/614922/195809393-e2bc0ed3-ab2c-4e41-b68c-fff22f9e909a.png)

**Comment by Kikky** [comment]
Ah..I understand. I can't use a field for search in the collection's page if this field is inside the tab (type: "tabs" field). Is it a normal behavior?

**Comment by jacobsfletch** [comment]
Hi @Kikky, very interesting. You should spin up a fresh `npx create-payload-app` and try and recreate the behavior with as few modifications as possible. Then potentially report this as a bug to Payload core based on your findings.

**Comment by jacobsfletch** [comment]
Hey @Kikky I'm going to close this issue for now because it sounds related to Payload core. Feel free to reference this issue from there.
