### ISSUE TITLE
Display added alt/title on Media when used 

### ISSUE THREAD

**Issue by Rar9** [payloadcms/plugin-seo#20]
Having installed the seo plugin this should alter the display of media so title /descriptions are showing on the uploaded image so they can be quickly altered

**Comment by jacobsfletch** [comment]
@Rar9 That's a great idea, I can totally see the value in this. This would be a feature for Payload core, though. Feel free to open a discussion [here](https://github.com/payloadcms/payload/discussions) or continue the conversation on Discord.
