### ISSUE TITLE
Text cursor jumps to end of content

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/plugin-seo#21]
In the `title` and `description` SEO fields, if you place the cursor and start to type anywhere in the existing content, you can only type 1 character then the cursor jumps to the end of the content.

Expected behavior is to be able to move the cursor and edit text anywhere, the current bug makes it very difficult to update existing text, you basically have to write it correctly the first time and make no updates.

Screen recording for demonstration:
https://user-images.githubusercontent.com/67977755/200879822-bc1b3160-6eec-4d53-b121-4d732f7bec3f.mov

**Comment by jacobsfletch** [comment]
Hi @JessChowdhury 😎

This ended up being a bug  in Payload core described [here](https://github.com/payloadcms/payload/issues/1393).
