### ISSUE TITLE
forms_1.useAllFormFields is not a function

### ISSUE THREAD

**Issue by shubhamwebdesign** [payloadcms/plugin-seo#27]
installed the plugin and got this error 
![image](https://user-images.githubusercontent.com/68468708/204717324-b1eaa0c4-ab25-49be-95d1-5770073c76a4.png)

**Comment by jacobsfletch** [comment]
@shubhamwebdesign ahh, yea I see the dependency versions are not correct. If you can bump your version of Payload past `v1.0.9` that should resolve your issue while we work out a fix.

**Comment by shubhamwebdesign** [comment]
Yes, after downgrading the payload version to v1.0.9 it started working again, thank you
