### ISSUE TITLE
Internalization

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/plugin-seo#4]
I'm using i18n in my Payload CMS. Is it possible to make the meta description and meta title fields localizable?

If not, could you treat this as a feature request?

**Comment by jacobsfletch** [comment]
Hey @AlessioGr 

We are planning on supporting localization for all Payload plugins. It's not currently supported, but I'll report back here once this is ready.

**Comment by jacobsfletch** [comment]
Hey @AlessioGr, `@payloadcms/plugin-seo@1.0.2` should fix this - it will be published shortly!

**Comment by Rar9** [comment]
Please add this to your description.
