### ISSUE TITLE
Allow custom more fields in SEO group?

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/plugin-seo#41]
I'm trying to use this plugin to replace our own implementation of seoMeta.

But we have more fields than this plugin. Could you allow add more fields as option like

<img width="700" alt="image" src="https://user-images.githubusercontent.com/5801015/225804970-0c05efcf-0fb7-4dfb-88c4-2e084dc5ccdd.png">

```
seo({
  overrides: {
   fields: [
     ...
   ]
  }
})
```

**Comment by jacobsfletch** [comment]
> Seems like this is in the roadmap at there is an _unused_ `fields` option on the PluginConfig type declaration.
> https://github.com/payloadcms/plugin-seo/blob/6bd04dfed2101663b20ff747e2e02a0cca362781/src/types.ts#L15

@ssyberg you're exactly right, that was an existing property but somehow was never used. I just opened #48 with the fix. 

@Stupidism I should be able to cut a release for this shortly so you can continue migrating to this plugin! I'll post an update here once that is done.

**Comment by jacobsfletch** [comment]
Just released in `1.0.12` 🚀
