### ISSUE TITLE
Nothing displaying in admin panel

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/plugin-seo#42]
Just added this plugin to an existing payload project running 1.6.17, and no matter how I change the config or what collections I specify I see no changes in the admin interface (have tried tabbedUI true and false).

Current config:
```
  plugins: [
    seo({
      collections: [
        Informationals,
      ],
      generateTitle: ({ doc }) => `${doc.title.value}`,
      generateDescription: ({ doc }) => doc.title
    }),
```

And here's the very simple test collection:

```
const Informationals = {
    slug: 'Informationals',
    admin: {
        useAsTitle: 'title',
        group: 'Pages',
    },
    fields: [
        {
          name: 'title',
          type: 'text',
          localized: true,
        },
    ]
}

export default Informationals;
```

Am I missing something obvious?

**Comment by jacobsfletch** [comment]
@ssyberg it looks like your plugin config is wrong, `collections` should be an array of slugs like this:
```ts
seo({
      collections: [
        'informationals',
      ],
      generateTitle: ({ doc }) => `${doc.title.value}`,
      generateDescription: ({ doc }) => doc.title
    }),
```

Let me know if this works for you!

**Comment by ssyberg** [comment]
I _just_ figured that out and came back to write it. Thanks!
