### ISSUE TITLE
Fields not rendering in collection when SEO is enabled since v1.0.12

### ISSUE THREAD

**Issue by davideperozzi** [payloadcms/plugin-seo#50]
After I've updated to v1.0.12 I can no longer see my own fields in my collections. I tried to debug it and found that adding this back worked for me. I didn't have the time to dig too much into the code. But maybe this helps :)
 
https://github.com/payloadcms/plugin-seo/pull/47/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L123

To reconstruct: 
- Create a collection
- Add fields, rows, tabs to the collection etc.
- Check if the fields are rendered properly without the plugin
- Add the seo plugin with those collections
- All the defined fields are gone

**Comment by jacobsfletch** [comment]
Ok just published a fix for this. Go ahead bump to `1.0.13` 🎉 And thanks again for the report, it is very helpful 🙌 .

**Comment by davideperozzi** [comment]
@jacobsfletch Happy to help:) thanks for the fix and payload in general!
