### ISSUE TITLE
How to access collection slug inside `generateURL`?

### ISSUE THREAD

**Issue by christopherpickering** [payloadcms/plugin-seo#53]
Thanks for the great too. I have a (probably very simple...) question about generating the URL with the `generateURL: ({ doc })` function.

I would like the generated urls to be like `https://example.com/<collection slug>/<doc slug>`.

From the doc (`generateURL: ({ doc, locale }) => {console.log(doc); return `https://example.com/${doc?.fields?.slug?.value}`) I cannot find any info about the parent collection. I'd really like to get its slug in there without adding another dummy field on the collection.

![image](https://github.com/payloadcms/plugin-seo/assets/17788706/97b72ae2-2a5a-41bf-bd38-3463ac36176f)

Do you know of an easy way? Thanks!

![](https://media.tenor.com/2LPylWKY4pEAAAAC/pingu-tanto-di-cappello.gif)

**Comment by jacobsfletch** [comment]
Hey @christopherpickering this was not possible before, but I just went ahead and added support for it just now! I released `v1.0.14-canary.0` just now so you can give it a try before the feature is generally available. Let me know how it goes!

**Comment by christopherpickering** [comment]
@jacobsfletch it works perfectly. Thank you!

**Comment by jacobsfletch** [comment]
Amazing! I should be able to get a patch version out for that sometime soon. Let me know if you experience anything unexpected as you use continue to use it.

**Comment by ficeco** [comment]
@jacobsfletch  I'm having issues getting this to work. I copied what was in the documentation but am getting "Cannot find name 'collection'" for ${collection?.slug}
